// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demo/service/crm_user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: userListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/add",
				Handler: roleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/edit",
				Handler: roleEditHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/change/enable/:id",
				Handler: roleChangeEnableHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/detail/:id",
				Handler: roleDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/crm/user/v1"),
	)
}
