// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	test09 "demo/service/test/api/internal/handler/test09"
	"demo/service/test/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test0901/one",
				Handler: test09.Test09Handler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test0901/two",
				Handler: test09.Test0902Handler(serverCtx),
			},
		},
		rest.WithPrefix("/api/test"),
	)
}
