Name: Product
Host: 0.0.0.0
Port: 8082

Mysql:
  DataSource: root:123456@tcp(192.168.0.34:3306)/go-zero?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: 127.0.0.1:6379
  Type: node # node可以不写，可以设为cluster
  # Pass: xxx # 如果有密码

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
    - 192.168.0.68:2379
    Key: product.rpc
  