// Code generated by goctl. DO NOT EDIT.
package types

type Foo struct {
	Foo int `json:"foo"`
}

type Bar struct {
	Bar int `json:"bar"`
}

type Response struct {
	Status  int64       `json:"status"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
