// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"study/docker/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: HomeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/env",
				Handler: EnvHandler(serverCtx),
			},
		},
	)
}
