// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cache "demo/gozero115/internal/handler/cache"
	elasticsearch "demo/gozero115/internal/handler/elasticsearch"
	group "demo/gozero115/internal/handler/group"
	redis "demo/gozero115/internal/handler/redis"
	user "demo/gozero115/internal/handler/user"
	"demo/gozero115/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: IndexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: group.IndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: cache.IndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cache"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: redis.IndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/redis"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: elasticsearch.IndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/es"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: user.IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
